### ISSUE TITLE
Support for loading fixture with binary data

### ISSUE THREAD

**Issue by smyrman** [uptrace/bun#360]
This is pretty specific... But my database model contains a very specific field type that only allows `Scan` from `[]byte` values:

https://pkg.go.dev/github.com/rs/xid@v1.3.0/b#ID

Example schema:

```go
import (
  xidb "github.com/rs/xid/b"
)

type User struct{
  ID xidb.ID
}
```
Fixture example:
```yaml
- model: User
  rows:
  - id: "c6stad4bcv4dggim7hr0" // XIDs have their own string-encoding that is used outside of the DB
```

This will result in the following error being triggered with type `"string"`:

https://github.com/rs/xid/blob/efa678f304ab65d6d57eedcb086798381ae22206/b/id.go#L36

Trying to add a fixture template method that returns `[]byte` will result in the same error (we still get a string value).

```
Fixture example:
```yaml
- model: User
  rows:
  - id: '{{ xidToBytes "c6stad4bcv4dggim7hr0" }}'
```

Is there a way one could either _skip_ running the `Scan` method for specific fields, or include a raw byte array in the yaml?

**Comment by vmihailenco** [comment]
I would improve xidb.ID to support `string`. That is a legit change so chances are the author of xid will accept such change. But you can also copy the wrapper and change your copy.

>Trying to add a fixture template method that returns []byte will result in the same error (we still get a string value).

I am surprised this does not work. I could try to debug this if you can prepare and an example that reproduces the problem.

The code is at https://github.com/uptrace/bun/blob/master/dbfixture/fixture.go#L247

**Comment by smyrman** [comment]
> I am surprised this does not work. 

Well, I a can't say that I am. We are using _quotes_ to wrap the template, so doesn't that mean that it will _always_ be interpreted as a string? I don't see how we _could_ use functions to return anything that is to be interpreted as something else than a string, right?

FWIW, not wrapping the template in quotes will result in a YAML error, as YAML sees it as an invalidly formatted JSON blob.

> I could try to debug this if you can prepare and an example that reproduces the problem.

Here is an example (feel free to close the PR, just easier to provide and example for you to see this way).

- #362

Example:

```
 go run .                                                                                                                                                                                                                                                                                                  :(
[bun]  09:24:14.281   DROP TABLE              536µs  DROP TABLE IF EXISTS "users"
[bun]  09:24:14.282   CREATE TABLE            332µs  CREATE TABLE "users" ("id" VARCHAR NOT NULL, "name" VARCHAR, "email" VARCHAR, "attrs" VARCHAR, "created_at" TIMESTAMP, "updated_at" TIMESTAMP, PRIMARY KEY ("id"))
panic: dbfixture: decoding id failed: xid: scanning unsupported type: string

goroutine 1 [running]:
main.main()
	/Users/smyrman/Code/bun/example/fixture-xid/main.go:68 +0xace
exit status 2
```


> I would improve xidb.ID to support string. That is a legit change so chances are the author of xid will accept such change. But you can also copy the wrapper and change your copy.

This is _definitively_ a problem we can work-around. We could do our own ID type, and then we could add code to scan from string as well as bytes.

However, I am not sure it's necessarily a reasonable change upstream though. It would perhaps be _weird_ for the binary optimized version to also accept a string when it doesn't encode content to strings. In fact, `xid/b.ID` is a wrapper to `xid.ID` that is written for a very specific purpose: provide binary optimized storage of the xid format (re-implementing both `Scan` and `Value`). The longer string-encoding is a lower-case base32 encoded string and does not matching the serialization formats that databases use for passing binary data in SQL. Thus accepting string input might just end-up with people using the binary optimized type against a `TEXT` field instead of `BYTEA` which will  not only consume more space as this stores the base64 encoded binary value, but it will _break_ the sortable expectation that the XID is designed for (both the raw binary and the base32 string encoding is sorable; base64 encoding is not).

**Comment by smyrman** [comment]
PS! I am very happy with bun in General.

**Comment by vmihailenco** [comment]
>We are using quotes to wrap the template, so doesn't that mean that it will always be interpreted as a string?

Yes, but I had the same problem with `time.Time` type so I've implemented special logic that calls function directly bypassing the text/template. https://github.com/uptrace/bun/pull/363 expands that logic even more and should make your example work.

>Thus accepting string input might just encourage people to use the binary optimized type against a TEXT field instead of BYTEA in SQL

It is true for some (most) databases, but some of them don't make any difference between string/bytes (just like Go).

>PS! I am very happy with bun in General.

Glad you like it :+1:

**Comment by smyrman** [comment]
Cool! I will try it out.

I started writing this before I saw your PR, but might as well share it anyways.

This is a _different approach_ to solving the problem, don't know if it's relevant. 

## 1: Choose parsing method

Choose parsing method per model in the fixture.

E.g. instead of:

```yaml
- model: User
  rows:
    - _id: smith
      id: '{{ xidToBinary "c6tf4i4bcv4458gu19s0" }}'
      name: John Smith
      email: john@smith.com
      attrs: { foo: bar, bar: baz }
      created_at: '{{ now }}'
      updated_at: '{{ now }}'
    - _id: doe
      id: '{{ xidToBinary "c6tf4i4bcv4458gu19s0" }}'
      name: Jonh Doe
      email: john@doe.com
      created_at: '{{ now }}'
 ```
 
 Allow (notice camel-case `createdAt` etc):
 
 ```yaml
- model: User
  parse_as: json # Allow e.g.: db, json, yaml
  rows:
    - _id: smith
      id: "c6tf4i4bcv4458gu19s0"
      name: John Smith
      email: john@smith.com
      attrs: { foo: bar, bar: baz }
      createdAt: '{{ now }}'
      updatedAt: '{{ now }}'
    - _id: doe
      id: "c6tf4i4bcv4458gu19s0"
      name: Jonh Doe
      email: john@doe.com
      createdAt: '{{ now }}'
 ```
 
 Pros:
 - Many types already implement "user-facing" decoding from JSON.
 
 Cons:
 - Does not solve allowing functions that return other formats than string.
