### ISSUE TITLE
YAML fixtures should provide a better way to work with sql.Null*

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/bun#59]
E.g. it should be possible to use YAML null. Model:

```go
type User struct {
    UpdatedAt sql.NullBool
}
```

Fixture:

```yaml
- model: User
  rows:
    - _id: admin
      updated_at: null
```

Also https://github.com/uptrace/bun/issues/17
